# Generated by Django 5.1.6 on 2025-02-22 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
